### PR TITLE
Gives credit to store and vuton

### PR DESCRIPTION
**Pull request by Sheshank-s**
You must give credit to our store, give credit by merging this pull request.

If you don't do this, we have the right to sue you.

### CODE REVIEW

**Comment by RedMAngo22** [comment]
I Did!

**Comment by Sheshank-s** [comment]
Okay thanks, you can close this pull request now.

**Comment by RedMAngo22** [comment]
BTW: You Have Write Acess

**Comment by Sheshank-s** [comment]
I do not, I accidently declined the invitation. Feel free to send another one, I will accept it.

**Comment by RedMAngo22** [comment]
_0

**Pull request closed without merging**
